### ISSUE TITLE
Ratscanner breaks discord go live streaming

### ISSUE THREAD

**Issue by amsmith525** [RatScanner/RatScanner#155] opened 2021-12-14 03:01 UTC
When running tarkov, discord, and ratscanner:

Upon starting go live streaming in discord, the stream is frozen. Closing ratscanner restores go live streaming.

Streaming whole monitor instead of tarkov is a workaround.

**Comment by Blightbuster** [comment] 2021-12-15 00:11
Unfortunately I am unable to reproduce this issue. Is the stream instantly freezing when you start it?

**Comment by amsmith525** [comment] 2021-12-15 23:23
The stream freezes immediately on starting ratscanner - except for the
mouse cursor.

**Comment by Blightbuster** [comment] 2021-12-16 01:55
Do you perhaps you a modified discord installation like BetterDiscord (I know I did experience freezes with BetterDiscord and some other applications in the past)

**Comment by amsmith525** [comment] 2021-12-16 02:33
Yes I use better discord - plugins are: hide channels, hidestreampreview,
pluginrep, zerespluginlibrary, bdfdb.

**Comment by Blightbuster** [comment] 2021-12-16 02:45
Could you please try to find out through trial & error if any of those plugins in specific causes this or if its just better discord in general. It seems to me that this is more of an issue with better discord than rat scanner so perhaps you should also file an issue on that project. The only thing I can imagine impacting better discord would be the fullscreen transparent overlay used by ratscanner (Basically a huge window which is on top of all other windows and used to render the overlay). Then again, this shouldnt stop better discord from streaming since its just another window.

**Comment by amsmith525** [comment] 2021-12-16 05:21
I've disabled all plugins, tried hardware accel off/on, css disabled, no
difference. I'll try removing better discord and see what happens.

**Comment by arall** [comment] 2021-12-31 11:42
I'm facing the same issue without any Discord plugins.

**Comment by InKahootz** [comment] 2022-01-04 03:09
Ditto. I've got the same issue as well as my buddies when RatScanner is open.

**Comment by Kerberos9** [comment] 2022-01-27 10:12
Hi, to add something to the issue and try to help, it seems that closing the Overlay part of RatScanner fixes it, I do it by holding ALT+TAB. This makes it so the in-game overlay doesn't work, but the window does still work, so I just put it in the second monitor and play like that. So I guess the Overlay process is like a placeholder that goes on top of Tarkov, and that breaks discord screen share.

![1643278027_RatScanner](https://user-images.githubusercontent.com/28060941/151337952-ba9fca76-b35b-4d1f-908d-e1b03f775d17.png)

**Comment by Blightbuster** [comment] 2022-01-28 16:39
I assume you are also using Better Discord?

**Comment by Kerberos9** [comment] 2022-01-28 17:00
> I assume you are also using Better Discord?

No, default discord with no modifications

**Comment by Blightbuster** [comment] 2022-01-28 17:46
Hmm I cant seem to reproduce this with my discord client:

### Steps
- Start RatScanner & EfT
- Go into discord channel and start stream of EfT application (not whole screen)

Nothing crashes, stream looks normal to me (didnt have a second person verify my stream though)


Stable 112296 (15f81ca) | Host 1.0.9003 | Windows 10 64-Bit (10.0.19042)

**Comment by Kerberos9** [comment] 2022-01-28 20:30
Just checked again just in case and I can reproduce it.

### Steps
- Start EFT and stream works perfectly
- Start RatScanner and stream changes to a static image (even when tabbed in and actually playing)
- Closing the Rat Scanner Overlay process (as shown in the image from my first comment) instantly makes it work correctly
- 
Stable 112296 (15f81ca) | Host 1.0.9003 | Windows 10 64-Bit (10.0.19044)

Also, window mode is Borderless.

**Comment by Blightbuster** [comment] 2022-08-31 00:51
From #384
> Hey, this issue is caused by discord not considering the transparency mode of windows.
>
> The rat scanner overlay works by showing a giant transparent window over you screen and when you stream an application with discord, discord thinks that the overlay window blocks the application and hence only shows black.
>
>To circumvent this, you can instead stream the screen (although this will not stream audio).
>
>From my end I unfortunately cant do much about it since any other way of showing the overlay (hooking into the game / another overlay) would'nt be taken lightly by the games anti cheat.

**Comment by InKahootz** [comment] 2022-08-31 02:20
@Blightbuster I came up with a solution (I do some SetWindowLong stuff in my [ReadySetTarkov](https://github.com/InKahootz/ReadySetTarkov) program. See my PR.

Tested it with my buddies who said my stream **was** working while I had RatScanner going but other confirmations from @amsmith525 and @Kerberos9 would be great!

**Closed** 2022-09-04 02:48 UTC
Labels: bug
