### ISSUE TITLE
Ratscanner disables discord streaming

### ISSUE THREAD

**Issue by WarlowAus** [RatScanner/RatScanner#430] opened 2022-09-10 05:10 UTC
**Describe the bug**
When using ratscanner, discord stream freezes. Sometimes it is instantly, sometimes it's a few seconds into the stream.
Obviously we're streaming tarkov in this instance, the app, not the screen. Switching tarkov to fullscreen fixes the issue, but as a co-incidence because it also disables the overlay.

Streaming to discord in fullscreen window without Rat Scanner started works without any issue. RatScanner is the issue.

**To Reproduce**
1. Start tarkov in a windowed fullscreen
2. Stream Borderless tarkov to discord channel
4. Test stream works with a friend
5. start ratscanner
6. stream will freeze promptly.

**Expected behavior**
Stream to discord will work and ratscanner will function in borderless window

**Screenshots**
Tough to screeny a frozen video

**Additional context**
Something to do with an update to tarkov, the Nvidia drivers or ratscanner caused an issue.
I havent tested this on non-nvidia GPUs, so can't confirm whether it's GPU driver related.

```

**Comment by WarlowAus** [comment] 2022-09-10 09:03
Also, multiple users are reporting the same thing on a variety of different hardware

**Comment by WarlowAus** [comment] 2022-09-11 11:41
More info, still testing. It seems there's two visual frames? One which overlays on the title of inspection windows for tarkov items and one discrete window. The Overlay that superimposes over the title space of an inspect window is the culprit. If you close this part of the overlay discord streaming works as per normal

**Comment by Blightbuster** [comment] 2022-09-11 19:55
Duplicate of #155.
Fixed in the latest version (v3.3.9)

Thanks for reporting and investigating never then less ❤️

**Closed by Blightbuster** 2022-09-11 19:55 UTC
Labels: bug, duplicate
