### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SirSweatyHands** [RatScanner/RatScanner#437] opened 2022-10-21 02:11 UTC
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
```
<details>
<summary>Log</summary>

```
[02:11:17.3541358] > [Warning] Config version (-1) is not supported!
[02:11:17.3833934] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()

```
</details>

**Comment by Blightbuster** [comment] 2022-10-23 18:11
Duplicate of #432, thanks for reporting never the less ❤️

**Closed by Blightbuster** 2022-10-23 18:11 UTC
Labels: duplicate
