### ISSUE TITLE
Downloading of file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json" failed.

### ISSUE THREAD

**Issue by monkeyman09** [RatScanner/RatScanner#102] opened 2021-07-09 00:38 UTC
**Error**
Downloading of file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json" failed.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\wendi\Downloads\rat scanner\Data\items.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)
```
<details>
<summary>Log</summary>

```
[00:38:21.7932714] > [Info]  ----- RatScanner 2.7.0 -----
[00:38:21.7978053] > [Info]  Starting RatScanner...
[00:38:21.7978565] > [Info]  Loading config...
[00:38:21.8218104] > [Info]  Loading item data...
[00:38:21.8275147] > [Info]  Loading resource "RSItemDataVersion"...
[00:38:22.1772799] > [Info]  A new item data version is available: 20210630
[00:38:22.1772898] > [Info]  Loading resource "RSItemDataLink"...
[00:38:22.2861653] > [Info]  Downloading file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json"...
[00:38:23.3773837] > [Error] Downloading of file "https://api.ratscanner.com/v3/file/items-en-30.06.2021.json" failed.
 -------------------- 
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\wendi\Downloads\rat scanner\Data\items.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at RatScanner.ApiManager.DownloadFile(String url, String destination)

```
</details>

**Comment by Blightbuster** [comment] 2021-07-09 00:39
Duplicate of #101

**Closed by Blightbuster** 2021-07-09 00:39 UTC
Labels: duplicate
