### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Thebrider** [RatScanner/RatScanner#433] opened 2022-10-07 19:18 UTC
**Error**
Object reference not set to an instance of an object.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
```
<details>
<summary>Log</summary>

```
[19:08:39.7254013] > [Warning] Config version (-1) is not supported!
[19:08:39.7901061] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
[19:08:42.1299523] > [Info]  Loading resource "RSGithubLink"...
[19:08:49.9948421] > [Warning] Config version (-1) is not supported!
[19:08:50.0773348] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
[19:09:00.6820054] > [Warning] Config version (-1) is not supported!
[19:09:00.7417524] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
[19:09:02.1179411] > [Info]  Loading resource "RSGithubLink"...
[19:10:07.6740467] > [Warning] Config version (-1) is not supported!
[19:10:07.7394268] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
[19:10:09.5349987] > [Info]  Loading resource "RSGithubLink"...
[19:10:11.0475466] > [Warning] Config version (-1) is not supported!
[19:10:11.1155073] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConfig()
   at RatScanner.View.BlazorUI..ctor()
   at RatScanner.PageSwitcher..ctor()
[19:13:39.3580094] > [Warning] Config version (-1) is not supported!
[19:13:39.4260398] > [Error] Object reference not set to an instance of an object.
 -------------------- 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at RatScanner.RatConfig.GetTarkovScreenConfig()
   at RatScanner.RatConfig.TrySetScreenConfig()
   at RatScanner.RatConfig.LoadConf
```
</details>

**Comment by Blightbuster** [comment] 2022-10-23 18:11
Duplicate of #432, thanks for reporting never the less ❤️

**Closed by Blightbuster** 2022-10-23 18:11 UTC
