### ISSUE TITLE
Can only call DragMove when primary mouse button is down

### ISSUE THREAD

**Issue by Oxylad** [RatScanner/RatScanner#267] opened 2022-01-09 21:04 UTC
**Error**
Unhandled exception (Application.Current.DispatcherUnhandledException)
```
System.InvalidOperationException: Can only call DragMove when primary mouse button is down.
   at System.Windows.Window.DragMove()
   at RatScanner.View.MinimalMenu.OnMouseDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam
```
<details>
<summary>Log</summary>

```
[18:10:32.1335801] > [Info]  ----- RatScanner 3.1.0 -----
[18:10:32.1338584] > [Info]  Starting RatScanner...
[18:10:32.1338677] > [Info]  Checking for new updates...
[18:10:32.1839083] > [Info]  Loading resource "RSClientVersion"...
[18:10:33.2337100] > [Info]  Loading config...
[18:10:33.2393913] > [Info]  Loading item data...
[18:10:33.2413596] > [Info]  Loading resource "RSItemDataVersion"...
[18:10:37.0760047] > [Info]  Loading TarkovTracker...
[18:10:37.8289380] > [Info]  Loading progress data...
[18:10:38.1719293] > [Info]  Loading price data...
[18:10:38.9353784] > [Info]  Setting default item...
[18:10:38.9355281] > [Info]  Initializing RatEye...
[18:10:54.5657684] > [Info]  Initializing hotkey manager...
[18:10:54.5674052] > [Info]  Setting up data update routines...
[18:10:54.5674425] > [Info]  Ready!
[18:15:54.5680607] > [Info]  Refreshing TarkovTracker DB...
[18:20:55.1196107] > [Info]  Refreshing TarkovTracker DB...
[18:25:55.7703907] > [Info]  Refreshing TarkovTracker DB...
[18:30:56.1145525] > [Info]  Refreshing TarkovTracker DB...
[18:35:56.6140833] > [Info]  Refreshing TarkovTracker DB...
[18:40:54.5689395] > [Info]  Refreshing Market DB...
[18:40:57.1491088] > [Info]  Refreshing TarkovTracker DB...
[18:45:57.6634061] > [Info]  Refreshing TarkovTracker DB...
[18:50:58.1460422] > [Info]  Refreshing TarkovTracker DB...
[18:55:58.7388468] > [Info]  Refreshing TarkovTracker DB...
[19:00:59.3496186] > [Info]  Refreshing TarkovTracker DB...
[19:05:59.8025725] > [Info]  Refreshing TarkovTracker DB...
[19:10:55.1171583] > [Info]  Refreshing Market DB...
[19:11:00.3382464] > [Info]  Refreshing TarkovTracker DB...
[19:16:00.7795920] > [Info]  Refreshing TarkovTracker DB...
[19:21:01.2961757] > [Info]  Refreshing TarkovTracker DB...
[19:26:01.6977878] > [Info]  Refreshing TarkovTracker DB...
[19:31:02.1369430] > [Info]  Refreshing TarkovTracker DB...
[19:36:02.5447828] > [Info]  Refreshing TarkovTracker DB...
[19:40:55.7280018] > [Info]  Refreshing Market DB...
[19:41:03.0690051] > [Info]  Refreshing TarkovTracker DB...
[19:46:03.6005516] > [Info]  Refreshing TarkovTracker DB...
[19:51:04.2386883] > [Info]  Refreshing TarkovTracker DB...
[19:56:04.8986421] > [Info]  Refreshing TarkovTracker DB...
[20:01:05.3838277] > [Info]  Refreshing TarkovTracker DB...
[20:06:05.9632416] > [Info]  Refreshing TarkovTracker DB...
[20:10:56.3171116] > [Info]  Refreshing Market DB...
[20:11:06.4750050] > [Info]  Refreshing TarkovTracker DB...
[20:16:06.9297236] > [Info]  Refreshing TarkovTracker DB...
[20:21:07.3681166] > [Info]  Refreshing TarkovTracker DB...
[20:26:07.8842431] > [Info]  Refreshing TarkovTracker DB...
[20:31:08.4452238] > [Info]  Refreshing TarkovTracker DB...
[20:36:08.8816297] > [Info]  Refreshing TarkovTracker DB...
[20:40:56.9146463] > [Info]  Refreshing Market DB...
[20:41:09.3177470] > [Info]  Refreshing TarkovTracker DB...
[20:46:09.7563717] > [Info]  Refreshing TarkovTracker DB...
[20:51:10.4148472] > [Info]  Refreshing TarkovTrack
```
</details>

**Comment by Blightbuster** [comment] 2022-01-20 15:26
Are you using any macro or other software to emulate mouse movement?

**Comment by Oxylad** [comment] 2022-01-20 15:28
A macro on my g502 that is binded to f24 that's all

**Comment by Blightbuster** [comment] 2022-01-20 15:29
Could you tell me when / how exactly this error appears? I assume you just move the minimal ui and it pops up?

**Comment by Oxylad** [comment] 2022-01-20 15:42
Yeah that was what happened

**Comment by Oxylad** [comment] 2022-01-20 15:44
Also is it normal that rat scanner interferes with GeForce instant replay recordings bcz when I have ratscanner on, it makes some black flashes in the recording?

**Comment by Blightbuster** [comment] 2022-01-20 15:45
I havent heard of that issue yet but it could be possible. Does that also happen with shadow play recordings?

**Comment by Oxylad** [comment] 2022-01-20 15:49
Yes shadow play

**Comment by Blightbuster** [comment] 2024-08-21 21:50
Since the issue never came up again and I can also not reproduce it, I'll have to assume it has be silently fixed in a version afterwards.
Please comment if the issue does indeed persist.

**Closed by Blightbuster** 2024-08-21 21:50 UTC
Labels: bug
