### ISSUE TITLE
Stuttering since new RatScanner Version 3.5.3

### ISSUE THREAD

**Issue by Deramond** [RatScanner/RatScanner#467] opened 2023-01-15 23:28 UTC
I sometimes get extreme stuttering while using RatScanner in Version 3.5.3, the previous version did not cause any problems.
Sometimes my GPU utilzation shoots up to 100% when quick scanning oder info scanning an item.
In other cases it drops my usage to under 10%.
All the problems do not occure when i dont use RatScanner.

CPU: 5800X3D
GPU: RTX 4090 - 3840x2160 - nvidia driver 528.02
Windows 11 - 22H2

**Comment by Blightbuster** [comment] 2023-01-16 00:53
Hey, could you start rat scanner, wait for the stuttering to happen and then send me the log file? (It's called log.txt and in the rat scanner folder)

**Comment by Deramond** [comment] 2023-01-16 07:12
Hi, i startet RatScanner, then Tarkov, checked some items and had instant stuttering, then closed both and attached the logfile.
[Log.txt](https://github.com/RatScanner/RatScanner/files/10423325/Log.txt)

**Comment by Blightbuster** [comment] 2023-01-16 10:36
Ok so good thing is the stuttering is caused by rat scanner crashing and not some bad optimization. The bad thing is the error doesn't give me much to work with.

I assume the UI renders / you can see the bitcoin after it started?

**Comment by Deramond** [comment] 2023-01-16 12:05
I recorded a short video to demonstrate the issue.
You can see, the mouse cursor and the background image are stuttering while scanning with ratscanner. After i closed it, the problem is also gone.
The stuttering also occures just by running around on a map while ratscanner is open

https://www.youtube.com/watch?v=mBHmYaMartk

The Last update 3.5.4 did not solve this issue for me.

**Comment by Deramond** [comment] 2023-01-17 22:39
Since yesterday i also receive an error message.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/40267965/213027928-b4b83ced-5807-40e6-ba36-108a0a21a7d8.png">

**Comment by Blightbuster** [comment] 2023-01-18 10:41
Do you perhaps use some form of auto clicker or other macro for your mouse? It seems like the auto scan is giving you issues so to fix it you could just disable that in your settings.

**Comment by Deramond** [comment] 2023-01-18 19:26
i dont use any macros, i changed the scan key from Shift + left Click to a single key and will test it

**Comment by Blightbuster** [comment] 2024-09-11 20:24
I can only assume this was caused by RatScanners global mouse hook being blocked from processing due to it processing an item scan or silently crashing. This should be fixed in more recent version since the scanning is now async.

**Closed by Blightbuster** 2024-09-11 20:24 UTC
Labels: bug, performance
