### ISSUE TITLE
Discord stream turns black when ratscanner is active

### ISSUE THREAD

**Issue by Robinjanse44** [RatScanner/RatScanner#384] opened 2022-07-01 08:19 UTC
Description:
When streaming EFT in discord the stream turns black when ratscanner is running. When closing ratscanner the stream turns back to normal. When rebooting ratscanner the screen turns black again. 
This issue is with windowed,bordeless and full screen with multiple resolutions. 

Reproduction steps:
Start EFT
Start streaming using discord. (this should work)
Start Ratscanner.
See if the stream is still running

Expected behaviour:
The stream turns black as long as ratscanner is running

Screenshots:
Cant seem to make this.

**Comment by Blightbuster** [comment] 2022-07-02 01:00
Hey, this issue is caused by discord not considering the transparency mode of windows.

The rat scanner overlay works by showing a giant transparent window over you screen and when you stream an application with discord, it discord thinks that the overlay windows blocks the application and hence only shows black.

To circumvent this, you can instead stream the screen (although this will not stream audio).

From my end I unfortunately cant do much about it since any other way of showing the overlay (hooking into the game / another overlay) would'nt be taken lightly by the games anti cheat.

**Comment by BelvedereHenrique** [comment] 2022-07-02 12:18
I had the same issue. Turning it back to fullscreen mode fixed to me.

**Comment by EvanBuschor** [comment] 2022-07-12 03:55
> I had the same issue. Turning it back to fullscreen mode fixed to me.

Doesn't this disable rat scanner?

**Comment by Robinjanse44** [comment] 2022-07-12 07:35
> 

Yes and no. The scanner still scans but for me it wont show the data above the item. I need te look at the rat scanner UI on my other screen about the item info.

**Comment by Blightbuster** [comment] 2022-08-31 00:50
Closing this in favor or #155

**Closed by Blightbuster** 2022-08-31 00:50 UTC
Labels: duplicate
