### ISSUE TITLE
Unhandled exception in RatScanner 2.5.1

### ISSUE THREAD

**Issue by DenOcelot** [RatScanner/RatScanner#70] opened 2021-02-08 13:25 UTC
**Error**
Unhandled exception in RatScanner 2.5.1
```
System.ArgumentException: Lock was not correctly acquired / released.
   at RatScanner.RatScannerMain.set_ScanLock(Boolean value)
   at RatScanner.IconManager.OnDynamicCorrelationDataChange(Object source, FileSystemEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
<details>
<summary>Log</summary>

```
[12:43:11.3834605] > [Info]  ----- RatScanner 2.5.1 -----
[12:43:11.3843729] > [Info]  Starting RatScanner...
[12:43:11.3844614] > [Info]  Loading config...
[12:43:11.4036480] > [Info]  Loading price data...
[12:43:12.6239307] > [Info]  Setting default item...
[12:43:12.6309596] > [Info]  Initializing name scan...
[12:43:12.6312036] > [Info]  Loading OCR data...
[12:43:12.7290292] > [Info]  Initializing icon scan...
[12:43:12.7302817] > [Info]  Loading static icons...
[12:43:12.8842619] > [Info]  Loaded 1197/1197 icons successfully.
[12:43:12.8866034] > [Info]  Loading static correlation data...
[12:43:12.9056999] > [Info]  Loading dynamic correlation data...
[12:43:12.9441211] > [Info]  Loading dynamic icons...
[12:43:13.1871504] > [Info]  Loaded 1236/1236 icons successfully.
[12:43:13.1918206] > [Info]  Initializing file watcher for icon cache...
[12:43:13.1941038] > [Info]  Prewarming name tool tip...
[12:43:13.2539473] > [Info]  Prewarming icon tool tip...
[12:43:13.2851922] > [Info]  Initializing hotkey manager...
[12:43:13.2875415] > [Info]  Checking for new updates...
[12:43:13.2891109] > [Info]  Loading resource "RSClientVersion"...
[12:43:13.6495087] > [Info]  Ready!
[12:43:13.6729949] > [Info]  Loading resource "RSPatreon"...
[12:43:14.0314610] > [Info]  Loading resource "RSDiscord"...
[12:43:14.4225980] > [Info]  Loading resource "RSGithub"...
[12:43:58.4082463] > [Info]  Loading dynamic correlation data...
[12:43:58.4458803] > [Info]  Loading dynamic icons...
[12:43:58.7019069] > [Info]  Loaded 1237/1237 icons successfully.
[12:43:58.7068889] > [Info]  Loading dynamic correlation data...
[12:43:58.7086754] > [Info]  Dynamic correlation data already up to date
[12:43:58.7087843] > [Info]  Loading dynamic correlation data...
[12:43:58.7108627] > [Info]  Dynamic correlation data already up to date
[12:43:58.7109543] > [Info]  Loading dynamic correlation data...
[12:43:58.7161874] > [Info]  Dynamic correlation data already up to date
[12:54:48.7977681] > [Info]  Loading dynamic correlation data...
[12:54:48.8899467] > [Info]  Loading dynamic icons...
[12:54:50.3060487] > [Info]  Loaded 1238/1238 icons successfully.
[12:54:50.3226842] > [Info]  Loading dynamic correlation data...
[12:54:50.3260649] > [Info]  Dynamic correlation data already up to date
[12:54:50.3262076] > [Info]  Loading dynamic correlation data...
[12:54:50.3280690] > [Info]  Dynamic correlation data already up to date
[12:54:50.3281423] > [Info]  Loading dynamic correlation data...
[12:54:50.3303689] > [Info]  Dynamic correlation data already up to date
[13:00:29.1208057] > [Info]  Loading dynamic correlation data...
[13:00:29.2129974] > [Info]  Loading dynamic icons...
[13:00:30.1967437] > [Info]  Loaded 1239/1239 icons successfully.
[13:00:30.2182216] > [Info]  Loading dynamic correlation data...
[13:00:30.2205766] > [Info]  Dynamic correlation data already up to date
[13:00:30.2208405] > [Info]  Loading dynamic correlation data...
[13:00:30.2245506] > [Info]  Dynamic 
```
</details>

**Comment by Blightbuster** [comment] 2021-02-08 13:26
Duplicate of #68

**Closed by Blightbuster** 2021-02-08 13:26 UTC
Labels: duplicate
