### ISSUE TITLE
Unhandled exception in RatScanner 2.6.1

### ISSUE THREAD

**Issue by Cozmo25** [RatScanner/RatScanner#87] opened 2021-06-03 12:21 UTC
Error:

Downloading of file "https://gist.githubusercontent.com/jannik4/d132bb89a51bf4e1508c9e4341ce7d6c/raw/1a39ce3d9a2a2ee2446c7d82e9aefa88fbfe815b/items.json" failed.

**Comment by Blightbuster** [comment] 2021-06-03 13:56
Hey, I guess that this was caused by a bad internet connection on your end or a temporary outage of githubs cdn. In both cases it should be fixed by just trying again 😄 
If the issue persists, just add a comment and I will reopen it.

**Closed by Blightbuster** 2021-06-03 13:56 UTC
